name: Dev CI

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    environment: abc_classification_dev

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: |
          python - m pip install --upgrade pip

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests

      - name: Run mypy
        run: |
          mypy . --explicit-package-bases

      - name: Pylint
        run: |
          pylint . *py
          

          

